setwd(".")
meat = read.table("/home/zabolotsky/PycharmProjects/abbakumov/Shad_AD on Python_1_01/3_Protein Consumption in Europe/Protein Consumption in Europe_data.txt", header=T, sep="")
print(dim(meat))
meat[2:dim(meat)[2]]
meat[2:10] = scale(meat[2:10])
dist_meat = dist(meat[2:10])
clust_meat = hclust(dist_meat, "ward.D")
print(clust_meat)
plot(clust_meat)
plot(clust_meat, hang=-1, labels=meat[ ,1])
rect.hclust(clust_meat, k=6,  border="red")
groups = cutree(clust_meat, k=4)
print(groups)
table_groups = table(meat$Country,groups)
print(table_groups)
print(meat$Country[groups==1])
print(meat$Country[groups==2])
#print(meat$Country[groups==3])
#print(meat$Country[groups==4])
#print(meat$Country[groups==5])

print(names(clust_meat))
print(clust_meat$merge)
plot(1:24, clust_meat$height, type = "b")
