setwd("/home/zabolotsky/PycharmProjects/abbakumov/Shad_AD on Python_1_01/2_pretendent")
assess.01 = read.table("assess.dat", header=T, sep="")
dist.assess = dist(assess.01[3:12])
clust.assess = hclust(dist.assess, "ward.D")
print(clust.assess)
plot(clust.assess)
plot(clust.assess, hang=-1)
rect.hclust(clust.assess, k=4,  border="red")
groups = cutree(clust.assess, k=4)
print(groups)
print(colMeans(assess.01[groups==1, 3:12]))
print(colMeans(assess.01[groups==2, 3:12]))
print(colMeans(assess.01[groups==3, 3:12]))
print(colMeans(assess.01[groups==4, 3:12]))
print(names(clust.assess))
print(clust.assess$merge)
plot(1:17, clust.assess$height, type = "b")
