setwd("/home/zabolotsky/PycharmProjects/abbakumov/Shad_AD on Python_1_01/1_beverage")
beverage.01 = read.table("beverage_r.csv", header=T, sep=";", fileEncoding= "cp1251")
dist.beverage = dist(beverage.01[2:9])
clust.beverage = hclust(dist.beverage, "ward.D")
print(clust.beverage)
plot(clust.beverage)
plot(clust.beverage, hang=-1)
rect.hclust(clust.beverage, k=3,  border="red")
groups = cutree(clust.beverage, k=3)
print(groups)
print(colMeans(beverage.01[groups==1, 2:9])*100)
print(colMeans(beverage.01[groups==2, 2:9])*100)
print(colMeans(beverage.01[groups==3, 2:9])*100)
print(names(clust.beverage))
print(clust.beverage$merge)
plot(1:33, clust.beverage$height, type = "l")