x = read.table("/home/zabolotsky/abbakumov_r/R_занятие_06_регрессия/02_diamond/diamond.dat", header=F)
print(summary(x))
print(names(x))
print(dim(x))
print(head(x))
print(tail(x))
res0 = lm(V2~V1+I(V1^2), x)
res1 = lm(V2~V1^2, x)
res2 = lm(V2~V1, x)
print(res0)
print(res1)
print(res2)
print(summary(res0))
print(summary(res1))
print(summary(res2))
scatter.smooth(x$V1, x$V2)
par(mfrow=c(1,2))
boxplot(x$V1)
boxplot(x$V2)
plot(density(x$V1))
print(cor(x$V1, x$V2))
