x = read.table("/home/bognev/abbakumovr/R_занятие_06_регрессия/04_series_g/series_g.csv", header=T, sep=";")
plot(x$series_g, type="l")
x2 = ts(data = x[,2], frequency = 12, start = c(1949,1))
print(head(x2))
plot(x2)
x_HW = HoltWinters(x2, seasonal = "mult")
print(x_HW$fitted)
plot(x_HW)
plot(fitted(x_HW))
x_predict = predict(x_HW, n.ahead = 12)
print(x_predict)
ts.plot(x2, x_predict, x_HW$fitted[,1], col=c("blue", "green", "red"))

x = read.table("/home/bognev/abbakumovr/R_занятие_06_регрессия/03_ts_graphs/wine_Austral.dat", header=T, sep="\t")
plot(x$red, type="l")
x2 = ts(data = x[,2], frequency = 12, start = c(1980,1))
print(head(x2))
plot(x2)
x_HW = HoltWinters(x2, seasonal = "mult")
print(x_HW$fitted)
plot(x_HW)
plot(fitted(x_HW))
x_predict = predict(x_HW, n.ahead = 8)
print(x_predict)
ts.plot(x2, x_predict, x_HW$fitted[,1], col=c("blue", "green", "red"))

